export default [
  {
    name: 'me',
    title: 'Me',
    platforms: ['ios', 'android'],
    isFree: true,
  },
  {
    name: 'viking_helmet',
    title: 'Viking Helmet',
    platforms: ['ios', 'android'],
    isFree: true,
  },
  {
    name: 'stallone',
    title: 'Stallone',
    platforms: ['ios', 'android'],
    isFree: true,
  },
  {
    name: 'ping_pong',
    title: 'Ping Pong',
    platforms: ['ios', 'android'],
    isFree: false,
  },
  {
    name: 'humanoid',
    title: 'Humanoid',
    platforms: ['ios', 'android'],
    isFree: true,
  },
  {
    name: 'fire_effect',
    title: 'Fire Effect',
    platforms: ['ios', 'android'],
    isFree: true,
  },
  {
    name: 'emotion_meter',
    title: 'Emotion Meter',
    platforms: ['ios', 'android'],
    isFree: false,
  },
  {
    name: 'emotions_exaggerator',
    title: 'Emotion Exaggerator',
    platforms: ['ios', 'android'],
    isFree: true,
  },
  {
    name: 'look1',
    title: 'Look 1',
    platforms: ['ios', 'android'],
    isFree: true,
  },
  {
    name: 'look2',
    title: 'Look 2',
    platforms: ['ios', 'android'],
    isFree: true,
  },
  {
    name: 'aviators',
    title: 'Aviators',
    platforms: ['ios', 'android'],
    isFree: true,
  },
  {
    name: 'ball_face',
    title: 'Ball face',
    platforms: ['ios', 'android'],
    isFree: true,
  },
  {
    name: 'beard',
    title: 'Beard',
    platforms: ['ios', 'android'],
    isFree: true,
  },
  {
    name: 'beauty',
    title: 'Beauty',
    platforms: ['ios', 'android'],
    isFree: true,
  },
  {
    name: 'fairy_lights',
    title: 'Fairy Lights',
    platforms: ['ios', 'android'],
    isFree: false,
  },
  {
    name: 'background_segmentation',
    title: 'Background Segmentation',
    platforms: ['ios', 'android'],
    isFree: true,
  },
  {
    name: 'hair_segmentation',
    title: 'Hair Segmentation',
    platforms: ['ios'],
    isFree: true,
  },
  {
    name: 'flower_crown',
    title: 'Flower Crown',
    platforms: ['ios', 'android'],
    isFree: true,
  },
  {
    name: 'frankenstein',
    title: 'Frankenstein',
    platforms: ['ios', 'android'],
    isFree: true,
  },
  {
    name: 'lion',
    title: 'Lion',
    platforms: ['ios', 'android'],
    isFree: false,
  },
  {
    name: 'manly_face',
    title: 'Manly Face',
    platforms: ['ios', 'android'],
    isFree: true,
  },
  {
    name: 'plastic_ocean',
    title: 'Plastic Ocean',
    platforms: ['ios', 'android'],
    isFree: true,
  },
  {
    name: 'pumpkin',
    title: 'Pumpkin',
    platforms: ['ios', 'android'],
    isFree: false,
  },
  {
    name: 'scuba',
    title: 'Scuba Diver',
    platforms: ['ios', 'android'],
    isFree: false,
  },
  {
    name: 'tape_face',
    title: 'Tape Face',
    platforms: ['ios', 'android'],
    isFree: false,
  },
  {
    name: 'tiny_sunglasses',
    title: 'Tiny Sunglasses',
    platforms: ['ios', 'android'],
    isFree: true,
  },
  {
    name: 'topology',
    title: 'Topology',
    platforms: ['ios', 'android'],
    isFree: true,
  },
];
